name: docs-environment

channels:
  - conda-forge

dependencies:
  - pytest
  - plotly
  - scipy
  - numpy
  - matplotlib
  - cadquery
  - openmc
  - paramak
  - neutronics-material-maker
  - sphinx-autodoc-typehints
  - sphinxcadquery
