
# Builds a dockerimage and then runs tests from within the docker enviroment

name: CI with docker build
on:
  pull_request:
    branches:
    - main  # this takes around 90 mins to build the image, hence limiting to occational PRs

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build and test with Docker
        run: |
          docker build -t paramak-neutronics --build-arg cq_version=2.1 --build-arg compile_cores=2 .
          docker run --rm paramak-neutronics  /bin/bash -c "pytest tests/test_reactor_neutronics_pymoab.py -v"
          docker run --rm paramak-neutronics  /bin/bash -c "pytest tests/test_reactor_neutronics_cubit.py -v"
          docker run --rm paramak-neutronics  /bin/bash -c "tests/test_shape_neutronics.py -v"
          docker run --rm paramak-neutronics  /bin/bash -c "tests/test_reactor_neutronics.py -v"
          docker run --rm paramak-neutronics  /bin/bash -c "tests/test_neutronics_utils.py -v"
          docker run --rm paramak-neutronics  /bin/bash -c "tests/test_example_neutronics_simulations.py -v"
          docker run --rm paramak-neutronics  /bin/bash -c "tests/notebook_testing.py -v"
